### PR TITLE
Add email validation

### PR DESCRIPTION
**Pull request by enen92**
Add validate field to email submission

### CODE REVIEW

**Comment by enen92** [comment]
Regex taken from: http://www.w3resource.com/javascript/form/email-validation.php

**Comment by razzeee** [comment]
Can you leave it empty? I also know that there are some devs that enter their email a bit changed like with [at]  instead of @ is that something that's okay for us? @martijnKaijser

**Comment by MartijnKaijser** [comment]
not all either want to show their email address at all or even have it readily scrapable for spam bots. Email address is not mandatory imo

**Comment by enen92** [comment]
Yap, it does make sense. Closing this one :)

**Pull request closed without merging**
